services:
  # web server
  php-apache:
    image: php:5.6-apache-stretch
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      # app
      - ../src:/var/www/html/
    # nginx configs
    # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    # certificates
    # - ./nginx/ca/:/etc/nginx/ca/:ro
    #links:
    #  - fpm:__DOCKER_PHP_FPM__

  # # php-fpm
  # fpm:
  #   build: ./php-fpm
  #   ports:
  #     - "9000"
  #   volumes:
  #     - ../src:/usr/share/nginx/html
  #     # Your php.ini
  #     - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
  #   # environment:
  #   # Set your APP env variables here:
  #   # - APP_KEY=
  #   # - DB_HOST=
  #   # - DB_DATABASE=
  #   # - DB_USERNAME=
  #   # - DB_PASSWORD=
  #   links:
  #     - mysql:mysql

  # database
  mysql:
    image: mysql
    restart: always
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql so that it can be reused
      # every time the container is recreated
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
