services:
  # web server
  php-apache:
    build: ./php-apache
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      # app
      - ../src:/var/www/html/
    # nginx configs
    # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    # certificates
    # - ./nginx/ca/:/etc/nginx/ca/:ro
    links:
      - mysql:mysql

  # database
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql so that it can be reused
      # every time the container is recreated
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
